name: 'ESLint check'
on: [pull_request]

env:
  NODE_VERSION: lts/hydrogen

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          # Ensure we have the correct pnpm version
          corepack prepare pnpm@8.15.6 --activate
          # Install dependencies with patched dependencies
          pnpm install --no-frozen-lockfile
          # Update lockfile with patched dependencies
          pnpm install --lockfile-only

      - name: Lint
        run: pnpm lint --filter "@cowprotocol/*"
