name: Publish package to NPM

on:
  release:
    types: [published]

env:
  NODE_VERSION: lts/hydrogen

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Enable Corepack
        run: corepack enable
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.6
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@cowprotocol'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - run: bash workflows/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
