name: Unit tests & Coverage
on: [push, pull_request]

env:
  NODE_VERSION: lts/hydrogen
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.6
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: |
          mkdir -p test-results
          # Run tests for all packages and collect results
          pnpm run test:ci --filter="@cowprotocol/*" || true
          
          # Ensure test results exist for each package
          for pkg in pkg/*; do
            if [ -f "$pkg/package.json" ] && [ -f "$pkg/jest.config.js" ]; then
              mkdir -p "$pkg/test-results"
              if [ ! -f "$pkg/jest.results.json" ]; then
                echo '{"numFailedTestSuites":1,"numFailedTests":1,"numPassedTestSuites":0,"numPassedTests":0,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTodoTests":0,"numTotalTestSuites":1,"numTotalTests":1,"success":false}' > "$pkg/jest.results.json"
              fi
              # Copy results to root for aggregation
              cp "$pkg/jest.results.json" "test-results/$(basename $pkg).jest.results.json" || true
              [ -d "$pkg/coverage" ] && cp -r "$pkg/coverage" "test-results/$(basename $pkg)-coverage" || true
            fi
          done
          
          # Aggregate results at root level
          if [ ! -f jest.results.json ]; then
            echo '{"numFailedTestSuites":1,"numFailedTests":1,"numPassedTestSuites":0,"numPassedTests":0,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTodoTests":0,"numTotalTestSuites":1,"numTotalTests":1,"success":false}' > jest.results.json
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            jest.results.json
            test-results/
            coverage/

      - name: Comment test results
        uses: mattallty/jest-github-action@v1.0.3
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: echo "unit tests already executed"
          coverage-comment: false
          changes-only: false

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
