name: Unit tests & Coverage
on: [push, pull_request]

env:
  NODE_VERSION: lts/hydrogen
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.6
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          # Ensure we have the correct pnpm version
          corepack prepare pnpm@8.15.6 --activate
          # Install dependencies with patched dependencies
          pnpm install --no-frozen-lockfile
          # Update lockfile with patched dependencies
          pnpm install --lockfile-only

      - name: Run tests
        run: |
          # Create test results directory
          mkdir -p test-results
          mkdir -p coverage

          # Run tests for all packages
          pnpm run test:ci --filter="@cowprotocol/*"

          # Merge coverage reports
          pnpm exec nyc merge ./pkg/*/coverage ./coverage/coverage-final.json
          pnpm exec nyc report --reporter=lcov --reporter=text --temp-dir=./coverage

          # Copy test results
          find pkg -name "jest.results.json" -exec cp {} test-results/ \;

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            jest.results.json
            test-results/
            coverage/

      - name: Comment test results
        uses: mattallty/jest-github-action@v1.0.3
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: echo "unit tests already executed"
          coverage-comment: false
          changes-only: false

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
