name: Unit tests & Coverage

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: lts/hydrogen
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run tests
        run: |
          # Create test results directory
          mkdir -p test-results
          mkdir -p coverage

          # Run tests for all packages
          pnpm run test:ci

          # Create coverage directory if it doesn't exist
          mkdir -p coverage
          # Copy all lcov.info files to coverage directory
          find pkg -name "lcov.info" -exec cp {} coverage/ \;
          # Merge coverage reports
          pnpm exec nyc merge coverage coverage/coverage-final.json
          # Generate final lcov report
          pnpm exec nyc report --reporter=lcov --reporter=text --temp-directory=coverage

          # Copy test results from all packages
          find pkg -name "jest.results.json" -exec cp {} test-results/ \;

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            jest.results.json
            test-results/
            coverage/

      - name: Comment test results
        uses: mattallty/jest-github-action@v1.0.3
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: echo "unit tests already executed"
          coverage-comment: false
          changes-only: false

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
