name: Unit tests & Coverage

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: lts/hydrogen
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run tests for cow-common
        if: github.event_name == 'pull_request'
        run: cd pkg/cow-common && pnpm run test:ci -- --ci --json --coverage --testLocationInResults --outputFile=report.json
      - uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: report.json
          custom-title: "Coverage Report - cow-common"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-common

      - name: Run tests for cow-config
        if: github.event_name == 'pull_request'
        run: cd pkg/cow-config && pnpm run test:ci -- --ci --json --coverage --testLocationInResults --outputFile=report.json
      - uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: report.json
          custom-title: "Coverage Report - cow-config"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-config

      - name: Run tests for cow-order-book
        if: github.event_name == 'pull_request'
        run: cd pkg/cow-order-book && pnpm run test:ci -- --ci --json --coverage --testLocationInResults --outputFile=report.json
      - uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: report.json
          custom-title: "Coverage Report - cow-order-book"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-order-book

      - name: Run tests for cow-order-signing
        if: github.event_name == 'pull_request'
        run: cd pkg/cow-order-signing && pnpm run test:ci -- --ci --json --coverage --testLocationInResults --outputFile=report.json
      - uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: report.json
          custom-title: "Coverage Report - cow-order-signing"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-order-signing

      - name: Run tests for cow-trading
        if: github.event_name == 'pull_request'
        run: cd pkg/cow-trading && pnpm run test:ci -- --ci --json --coverage --testLocationInResults --outputFile=report.json
      - uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: report.json
          custom-title: "Coverage Report - cow-trading"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-trading

      - name: Run tests for cow-subgraph
        if: github.event_name == 'pull_request'
        run: cd pkg/cow-subgraph && pnpm run test:ci -- --ci --json --coverage --testLocationInResults --outputFile=report.json
      - uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: report.json
          custom-title: "Coverage Report - cow-subgraph"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-subgraph

      - name: Run tests for cow-composable
        if: github.event_name == 'pull_request'
        run: cd pkg/cow-composable && pnpm run test:ci -- --ci --json --coverage --testLocationInResults --outputFile=report.json
      - uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: report.json
          custom-title: "Coverage Report - cow-composable"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-composable

      - name: Run tests for cow-shed
        if: github.event_name == 'pull_request'
        run: cd pkg/cow-shed && pnpm run test:ci -- --ci --json --coverage --testLocationInResults --outputFile=report.json
      - uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: report.json
          custom-title: "Coverage Report - cow-shed"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-shed
