name: Unit tests & Coverage
on: [push, pull_request]

env:
  NODE_VERSION: lts/hydrogen
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        run: pnpm run test:coverage
        if: env.COVERALLS_REPO_TOKEN != ''
      - name: Run tests without coverage
        run: pnpm run test
        if: env.COVERALLS_REPO_TOKEN == ''

      - name: Comment in failing tests
        uses: mattallty/jest-github-action@v1.0.3
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'echo unit tests already executed'
          coverage-comment: false

      - name: Coveralls Report
        uses: coverallsapp/github-action@1.1.3
        if: (success() || failure()) && env.COVERALLS_REPO_TOKEN != ''
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
