name: Unit tests & Coverage

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: lts/hydrogen
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run tests and generate coverage reports
        if: github.event_name == 'pull_request'
        run: |
          mkdir -p coverage-reports
          for pkg in cow-common cow-config cow-order-book cow-order-signing cow-trading cow-subgraph cow-composable cow-shed; do
            echo "Running tests for $pkg"
            cd "pkg/$pkg"
            pnpm run test:ci
            if [ -f "coverage/coverage-final.json" ]; then
              cp coverage/coverage-final.json "../../coverage-reports/$pkg-coverage-final.json"
            else
              echo '{"numFailedTests":0,"numTotalTests":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTotalTestSuites":0,"numPassedTests":0,"numTodoTests":0,"startTime":0,"success":true,"testResults":[]}' > "../../coverage-reports/$pkg-coverage-final.json"
            fi
            cd ../..
          done

      - name: Generate coverage report for cow-common
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: coverage-reports/cow-common-coverage-final.json
          custom-title: "Coverage Report - cow-common"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-common
          test-script: pnpm run test:ci
          skip-step: all

      - name: Generate coverage report for cow-config
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: coverage-reports/cow-config-coverage-final.json
          custom-title: "Coverage Report - cow-config"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-config
          test-script: pnpm run test:ci
          skip-step: all

      - name: Generate coverage report for cow-order-book
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: coverage-reports/cow-order-book-coverage-final.json
          custom-title: "Coverage Report - cow-order-book"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-order-book
          test-script: pnpm run test:ci
          skip-step: all

      - name: Generate coverage report for cow-order-signing
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: coverage-reports/cow-order-signing-coverage-final.json
          custom-title: "Coverage Report - cow-order-signing"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-order-signing
          test-script: pnpm run test:ci
          skip-step: all

      - name: Generate coverage report for cow-trading
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: coverage-reports/cow-trading-coverage-final.json
          custom-title: "Coverage Report - cow-trading"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-trading
          test-script: pnpm run test:ci
          skip-step: all

      - name: Generate coverage report for cow-subgraph
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: coverage-reports/cow-subgraph-coverage-final.json
          custom-title: "Coverage Report - cow-subgraph"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-subgraph
          test-script: pnpm run test:ci
          skip-step: all

      - name: Generate coverage report for cow-composable
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: coverage-reports/cow-composable-coverage-final.json
          custom-title: "Coverage Report - cow-composable"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-composable
          test-script: pnpm run test:ci
          skip-step: all

      - name: Generate coverage report for cow-shed
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          coverage-file: coverage-reports/cow-shed-coverage-final.json
          custom-title: "Coverage Report - cow-shed"
          annotations: coverage
          output: comment, report-markdown
          working-directory: pkg/cow-shed
          test-script: pnpm run test:ci
          skip-step: all
